### ISSUE TITLE
menu_photo is sending null even with images attached

### ISSUE THREAD

**Issue by fil7er** [tastyigniter/ti-ext-api#10]
**Expected behavior:**
(get image url)

**Actual behavior:**
(getting null)

**Reproduce steps:**
(Attach any image to menu item and try to get json)

**Version:**
(3.0.4 API 0.2)

**Comment by fil7er** [comment]
Sorry this is not the API issue, it's from app itself. I have this workaround in database to TRIGGER every INSERT, UPDATE or DELETE in TABLE ti_media_attachments:
`UPDATE ti_menus
        INNER JOIN
    merits ON ti_menus.menu_id = ti_media_attachments.attachment_id 
SET 
    ti_menus.menu_photo = 'THE URL IS HERE'
WHERE
    ti_media_attachments.attachment_id =  ti_menus.menu_id;`

Please can help how find this full url attachment in database?

**Comment by annanoell** [comment]
Hi @fil7er , 
I faced the same issue and I've solved it adding the thumb in the `beforeSave` event of the menu model. I don't know if this is the best solution but it works for me know as I need the image in the API response.

_app>admin>models>Menus_model.php_
`protected function beforeSave()
    {
	    if(count($this->media) != 0){
		    $this->attributes['menu_photo'] = $this->media[0]->getThumb();
	    }
	}
`

This creates a thumbnail with no resize of the original image, you must add some options to resize it.

Hope it helps.

**Comment by fil7er** [comment]
> Hi @fil7er ,
> I faced the same issue and I've solved it adding the thumb in the `beforeSave` event of the menu model. I don't know if this is the best solution but it works for me know as I need the image in the API response.
> 
> _app>admin>models>Menus_model.php_
> `protected function beforeSave() { if(count($this->media) != 0){ $this->attributes['menu_photo'] = $this->media[0]->getThumb(); } } `
> 
> This creates a thumbnail with no resize of the original image, you must add some options to resize it.
> 
> Hope it helps.

It doens't delete the thumbnail if media is set none. But is so much better than using Trigger in sql, thanks!
