### ISSUE TITLE
Failed to authenticate with admin token

### ISSUE THREAD

**Issue by cecilwei** [tastyigniter/ti-ext-api#13]
**Expected behavior:**
Shall be able to invoke API with token created with `/api/admin/token`

**Actual behavior:**
Got the following error response when invoking API with token obtained by invoking `/api/admin/token`
`{"status_code":401,"message":"No valid API token provided.","debug":{"line":64,"file":"\/var\/www\/html\/extensions\/igniter\/api\/classes\/ApiController.php",`

**Reproduce steps:**
Create API token with the following command:
`curl -X POST --data "username=admin&password=123456&device_name=test" http://ourhost/api/admin/token`

And try to send request with the token:
 `curl -i -X GET -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer your-api-token" http://ourhost/api/orders`

Got 401 error response.

**Version:**
(TastyIgniter version v3 beta 22.2, API extension 0.2.0

**Additional Information:**
(Additional information, if any)

**Comment by cecilwei** [comment]
Just figured out that the authorization header was removed in .htaccess. Had to add

  ```
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
```
To keep the authorization header.

**Comment by APEX-BVI** [comment]
Hi there,

I am having a similar issue, and the your suggestions did not work for me...I feel that it was updated because when I opened the f.htaccess file, those lines were there...any other recommendation/suggestion?
