### ISSUE TITLE
API Tokens not validation in Apache

### ISSUE THREAD

**Issue by AcidBurp** [tastyigniter/ti-ext-api#20]
"Error 401 No valid API token provided." when using the API with valid tokens.

Known Larvel issue easily fixed by adding 2 lines to the .htaccess file. Unsure how to fix it on nginx but thought this might be usefull to share

RewriteCond %{HTTP:Authorization} ^(.*)

RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]

**Comment by ryanmitchell** [comment]
Thanks, I've opened a PR with an update for the docs
