### ISSUE TITLE
menu_option_values not returning

### ISSUE THREAD

**Issue by jubirajara** [tastyigniter/ti-ext-api#21]
Hi !
am i  missing something guys?

Using demo Data
Send this post
http://192.168.43.191/api/menus/1?include=categories,menu_options,menu_option_values
Returned without menu_option_values ,example in option drinks (coke and diet coke):
{
   "data" :
   {
      "menu_id" : 1,
      "menu_name" : "Puff-Puff",
      "menu_description" : "Traditional Nigerian donut ball, rolled in sugars",
      "menu_price" : 4.99,
      "menu_photo" : null,
      "stock_qty" : 997,
      "minimum_qty" : 3,
      "subtract_stock" : true,
      "menu_status" : true,
      "menu_priority" : 0,
      "order_restriction" : 0,
      "categories" :
      [
         {
            "category_id" : 1,
            "name" : "Appetizer",
            "description" : "RESed consequat, sapien in scelerisque egestas, neque nisi dapibus magna, non malesuada lectus ligula vel justo. Vestibulum felis nisi, tincidunt eu est quis, faucibus tincidunt ante.",
            "parent_id" : null,
            "priority" : 1,
            "image" : null,
            "status" : true,
            "nest_left" : null,
            "nest_right" : null,
            "permalink_slug" : "appetizer",
            "pivot" :
            {
               "menu_id" : 1,
               "category_id" : 1
            }
         }
      ],
      "menu_options" :
      [
         {
            "menu_option_id" : 1,
            "option_id" : 4,
            "menu_id" : 1,
            "required" : true,
            "priority" : 1,
            "min_selected" : 0,
            "max_selected" : 2,
            "option_name" : "Drinks",
            "display_type" : "checkbox",
            "option" :
            {
               "option_id" : 4,
               "option_name" : "Drinks",
               "display_type" : "checkbox",
               "priority" : 0
            }
         },
         {
            "menu_option_id" : 10,
            "option_id" : 3,
            "menu_id" : 1,
            "required" : true,
            "priority" : 0,
            "min_selected" : 0,
            "max_selected" : 2,
            "option_name" : "Size",
            "display_type" : "radio",
            "option" :
            {
               "option_id" : 3,
               "option_name" : "Size",
               "display_type" : "radio",
               "priority" : 0
            }
         }
      ]
   }
}

**Comment by ryanmitchell** [comment]
Sorry, only just seeing this

your include should be ?include=categories,menu_options,menu_options.menu_option_values

**Comment by jubirajara** [comment]
Worked like a charm!
thanks  you a lot and keep up with the great work
