### ISSUE TITLE
API to create tables

### ISSUE THREAD

**Issue by abhishiv** [tastyigniter/ti-ext-api#28]
**Expected behavior:**
Expected defs for tables in ti-ext-api/docs/
**Actual behavior:**
absent

**Version:**
latest

**Comment by ryanmitchell** [comment]
What’s your use case for this functionality? 

We aim to only provide api end points for common functions to limit the need to support the code.

**Comment by sampoyigi** [comment]
@ryanmitchell we should probably add a new endpoint for Tables (since we have for both menu items and orders?).. I always miss things on the reservation side 😅 .

**Comment by ryanmitchell** [comment]
Ok leave it with me and I’ll work on it in the next week or so. Will try and do it for the next release

**Comment by sampoyigi** [comment]
Cool stuff!

**Comment by ryanmitchell** [comment]
I could complicate it some more by asking.... should Tables not be part of the reservation extension? Both API end points but also the admin side of things?

**Comment by ryanmitchell** [comment]
This PR should fix it: https://github.com/tastyigniter/ti-ext-api/pull/29
