### ISSUE TITLE
How to Create an order with API

### ISSUE THREAD

**Issue by nyousefzai** [tastyigniter/ti-ext-api#36]
Create Order with API

**Actual behavior:**

No Documentation 
This endpoint allows you to list, retrieve, update and delete your orders, I assume we can do "create" too.

@ryanmitchell  even the new [ https://github.com/tastyigniter/ti-ext-api/tree/integrate-dingo-api ](https://github.com/tastyigniter/ti-ext-api/tree/integrate-dingo-api) is not clear how to create an order with how to pass menu items...

I propose we use [postman](https://learning.postman.com/docs/publishing-your-api/documenting-your-api/) or an equivalent tool to make the online documentation for this API.  

just want to take the opportunity and thank everyone involved in this project.

**Comment by ryanmitchell** [comment]
If you have a look at the new branch - https://github.com/tastyigniter/ti-ext-api/tree/integrate-dingo-api - which will be the next API release, you'll see there are docs there to describe it.

**Comment by ryanmitchell** [comment]
Did you look at the orders.md file in the docs folder? There are sample payloads.

**Comment by nyousefzai** [comment]
Yeah I saw the orders.md when i am sending  `{uri}/api/orders` route i get 
"status_code": 500,
"message": "Array to string conversion",

**Comment by ryanmitchell** [comment]
Can you attach your payload?

**Comment by nyousefzai** [comment]
```{
  "order_id": 5,
  "customer_id": 1,
  "location_id": 1,
  "address_id": null,
  "first_name": "Tucker",
  "last_name": "Vega",
  "email": "vavur@mailinator.com",
  "telephone": "+1 (604) 376-2674",
  "notify": null,
  "order_type": "collection",
  "order_date_time": "2020-05-24 13:13:00",
  "processed": true,
  "total_items": 3,
  "order_total": 15.0449,
  "comment": "",
  "payment": "cod",
  "invoice_prefix": "INV-2020-00",
  "invoice_date": "2020-05-24T11:58:43.000000Z",
  "status_id": 3,
  "status_updated_at": "2020-05-24T11:58:43.000000Z",
  "assignee_id": null,
  "assignee_group_id": null,
  "assignee_updated_at": null,
  "ip_address": "192.168.10.1",
  "hash": "7158b25ef2f10b151f87fc4d26b3b27d",
  "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:76.0) Gecko/20100101 Firefox/76.0",
  "date_added": "2020-05-24 12:58:43",
  "date_modified": "2020-05-24 12:58:43",
  "order_totals": []
}```

**Comment by ryanmitchell** [comment]
On my phone so can’t fully respond until next week but there are quite a few incorrect fields - order date time for example should be order date and order time. I don’t think you should be passing order totals either. 

Are you using the new branch of the Api I directed you to? Quite a lot has changed so I need to know which you are working with.

Give me a few days and I’ll get back to you with a correct payload.

**Comment by nyousefzai** [comment]
@ryanmitchell  thanks, I figured out here is a reference payload  just in case someone else faces the same issue
   
      ```{
  "order_id": 7,
  "customer_id": null,
  "location_id": 2,
  "address_id": null,
  "first_name": "Tucker",
  "last_name": "Vega",
  "email": "vavur@mailinator.com",
  "telephone": "+1 (604) 376-2674",
  "order_type": "collection",
  "processed": true,
  "total_items": 3,
  "order_total": 15.0449,
  "comment": "test",
  "payment": "cod",
  "invoice_prefix": "INV-2020-00",
  "invoice_date": "2020-05-24T11:58:43.000000Z",
  "status_id": 3,
  "status_updated_at": "2020-05-24T11:58:43.000000Z",
  "assignee_id": null,
  "assignee_group_id": null,
  "assignee_updated_at": null,
  "ip_address": "192.168.10.1",
  "date_added": "2021-05-24 12:58:43",
  "date_modified": "2021-05-24 12:58:43",
  "cart": [
        {
            "name": "Napoli",
            "price": 10,
            "quantity": 1
        }
    ]
}

**Comment by nyousefzai** [comment]
@ryanmitchell  whenever you get the chance plz provide a sample payload to create an order in the correct way, also how you would define the menu option? thanks

**Comment by ryanmitchell** [comment]
The sample will be included in the docs for the next API release.

**Comment by ryanmitchell** [comment]
The sample will be included in the docs for the next API release.

**Comment by nyousefzai** [comment]
cool

**Comment by waltermvp** [comment]
@ryanmitchell  did the docs ever get updated with the sample post body?
