### ISSUE TITLE
Securing API using Laravel Sanctum

### ISSUE THREAD

**Issue by ryanmitchell** [tastyigniter/ti-ext-api#4]
I see in the roadmap you mentioned securing the API using passport, so I thought it may be helpful to mark out the steps and highlight questions as there is a lot of overlap with the main core code.

### Installation 
https://laravel.com/docs/7.x/passport#installation
Involves composer and artisan commands - are these run once on the repo, or is it something thats added to a build script?

Then it requires us to add the `Laravel\Passport\HasApiTokens` trait to the `App\User` model (`App\Admin\Users_model` ?).

Then call the `Passport::routes` method within the boot method of your AuthServiceProvider. There doesnt seem to be an AuthServiceProvider for TastyIgniter?

Finally, in your `config/auth.php` configuration file, you should set the driver option of the api authentication guard to passport. There doesnt seem to be such a configuration file in TastyIgniter?

### Deploying 
When deploying Passport to your production servers for the first time, you will likely need to run the `passport:keys` command. This command generates the encryption keys Passport needs in order to generate access token. This would need to be built into the install scripts?

### Managing
To manage clients we will need to create models that interface with the JSON API they supply, rather than the database, so most of the code will be front end.
See: https://laravel.com/docs/7.x/passport#managing-clients

@sampoyigi I'm happy to work on this if you feels its of value and you can direct me a bit.

**Comment by sampoyigi** [comment]
@ryanmitchell just seeing this now, I'll have a proper response after I wake up its a bit late now. :)

**Comment by sampoyigi** [comment]
Thank you for the steps and effort :) It's definitely of value and we can sure work together on it. 

The only drawback I have with Laravel Passport is that it provides an OAuth2 server implementation which is a bit too much, I feel what we need is a basic authentication system which Laravel Sanctum provides. I have only read about Sanctum since it was released, do you think we can use it instead?

**Comment by ryanmitchell** [comment]
Just looked at the docs now and it looks more inline with what I would expect the system to have. 

We would just need to set up a new listing for editing/adding tokens in the backend and the rest seems to be addition of the sanctum middleware? Seems simpler.

**Comment by sampoyigi** [comment]
Yep, it's def simpler and we add an admin page for the tokens and probably implement our own middleware to authenticate incoming requests as it seems the Sanctum middleware only works for the SPA Authentication scenario or maybe not. Also registering the routes and migrations. How do we start?

**Comment by ryanmitchell** [comment]
The middleware here should work? but you know better than me!

https://laravel.com/docs/7.x/sanctum#protecting-routes

If so I can have a go and getting this up and running and ping you if I need any guidance or come up against issues. You have lots of other things to be working on. Does that work as an approach?

**Comment by sampoyigi** [comment]
Sure let's do that :)

**Comment by ryanmitchell** [comment]
Ok, I've spent some time on this and am coming up against something I could do with your help on.

Steps so far:
Updated composer.json to include
   ```
"laravel/framework": "^6.0",
"laravel/sanctum": "~2.2",
```
Ran sanctum installation as per the docs, which worked fine - can see the database table ('personal_access_tokens').

Have sanctum creating API tokens for admin users (added use HasApiTokens to Admin\Models\Users_model.php, and created a new end point in routes.php as per "Mobile Application Authentication" in the documentation).

Added middleware ('auth:sanctum') on ext-api/routes.php file - this is where the issues begin.

Sanctum expects to use Auth for the user authentication, which poses 2 problems:

1. Auth is the customers model, not the Admin users model (I 'fixed' this by changing registerSingletons() in ServiceProvider.php to return Admin users for auth and customer.auth for Customer - but this obviously would mean needing elsewhere).
 
2. Admin users model doesn't seem to extend Laravel Auth, which means there is no viaRequest method which Sanctum hooks into. I don't know if this is as a consequence of the upgrade to 6.0 and a different way of doing things.

Any help on either of the above would be great  - in the mean time I can keep going on other aspects like creating tokens.

**Comment by sampoyigi** [comment]
Thought I responded to this yesterday. 

Instead of the direct changes to the Users_model, we can create a new model to extend Users_model and add the HasApiTokens to it. 

On the auth part, I feel extending the SanctumServiceProvider will be a better approach? Open a PR so I can help with the auth part.

I'd push the PR from a new branch so you can still push other changes while you work on the sanctum changes from the new branch. I always go back to this [tutorial](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) when I'm lost on the whole gitflow thing.

**Comment by ryanmitchell** [comment]
@sampoyigi 

See: https://github.com/tastyigniter/ti-ext-api/pull/5

 I've done a little more work on this. 

1. Extended SanctumServiceProvider and am able to override configureGuard() to allow us to do custom logic. If we want Admin users to be able to access the api then I need some guidance as to how to handle the Auth::resolved line in ApiProvider.php as changing to to AdminAuth::resolved throws a function error (Function name must be a string).

2. Added ApiMiddleware.php - we may not need this, remains to be seen.

3. Registered the service provider on the fly in registerResponseFactory() of Extension.php, to avoid needing to amend any of the core code.

4. Extends Users model as discussed (ApiUsers.php).

Still to be resolved (asides from the admin issue above) - are we going to allow Admin and nonAdmin users to access the API, if so, the custom provider will need to handle it in the configureGuard() method.

Let me know your thoughts so I can work out how best to go forward.

**Comment by sampoyigi** [comment]
Looking good so far.  👍 

You can register the service provider within its own method `registerSanctum`. 

To allow unauthenticated admin access, we could add a new key to the $restConfig to enable/disable authentication at the controller level. Authentication should be enabled by default though.

Let me pull the PR to review the code.

**Comment by ryanmitchell** [comment]
Thanks

To clarify the what I meant about admin users - There are two types of Auth users on TI (correct me if I’m wrong). 

1. Regular users
2. Admin/staff users

The API needs to allow both user types to authenticate against and call the API.

**Comment by sampoyigi** [comment]
Gotcha! You meant for both customer and admin, we can resolve that in the configureGuard method as you suggested.

**Comment by sampoyigi** [comment]
Did a bit of work.

Moved the SanctunServiceProvider logic into Extension class.

Used the ApiMiddleware in place of `auth:sanctum` since TI has its own Auth implementation and doesn't use auth guards. I'm not 100% on this approach but let me know what you think.

Extended both Users_model & Customers_model with HasApiTokens so make the trait methods accessible, see `sanctumConfigureAuth()` method. A bit hacky, maybe there's a better approach?

Added the config/sanctum.php files and migration file.

Haven't figured how to issue tokens yet but let me know your thoughts anyways :)

**Comment by ryanmitchell** [comment]
This is great - moving things on well. I've pushed a couple of changes and additions.

Went back to using ApiUsers and ApiCustomers rather than the traits - if you look at routes.php now you'll see why - it allows tokens to be issued by a user authenticating against /token and /token/admin. I've been able to issue a token on my dev setup and verify its working when making a call with the right HTTP headers, so it looks like the middleware is working well.

My only question is around line #26 in ApiMiddleware.php

`        $this->auth = app(app()->runningInAdmin() ? 'admin.auth' : 'auth');
`

Will it ever be runningInAdmin() --> true ? This line may be redundant...

If you're happy with this approach then I can get to work on the output of the backend and starting to limit the scope of tokens.

**Comment by ryanmitchell** [comment]
More work here: https://github.com/tastyigniter/ti-ext-api/pull/5

There is now an admin view to list and delete/revoke any tokens issued.

I've added the ability to authorisation to be toggled on/off per action and resource, which gives great flexibility. I'm not sure if what I've done is the 'right' way, but its working and I'm happy to change it if there is a way I've missed.

From a functionality point of view, I think this is everything I feel we need to achieve at this point. 

Let me know if you want me to change or improve anything.

**Comment by sampoyigi** [comment]
Great additions and happy with your approach on authorization per actions.

Yup, you're right with line #26 in ApiMiddleware.php.
 
I've refactored how tokens are issued. I know I suggested extending the core models but just doesn't sit right and could break morph relations. Developers can still extend the core models or use the HasApiToken traits if they want. Do we need to make the current user available through the auth manager?

Renamed authorisation to authorization, I like the sound of `zzz` in authorization :)

**Comment by ryanmitchell** [comment]
Yeah this is all great - definitely simpler and thats always a good thing. I've pushed the language pack update and a bug fix on the model.

Yes I think it would be good to make the current user available, and we also need to limit the output on some of the resources (e.g. orders, customers) if the user is a customer, as it should only return the elements relevant to them - if you can give me a pointer on both of those I'll do it.

Is it worth doing anything with the 'abilities' at this point, we could allow them to pass the names of the resources + actions they want to be able to (or * for all) at the point the token is set up? e.g. {'orders':['index', 'store'],'customers':['index']...} ? its not something I need but someone else might.

**Comment by sampoyigi** [comment]
Within the controller, you can apply a scope to the query to limit the output. If the current access token `ApiManager::currentAccessToken()` is a customer then chain a `where('customer_id')` scope to the query or something like that. 

To make the current user available, use `app('auth' or 'admin:auth')->setUser()` at some point after authenticating the token.

Yea lets implement the abilities, using the same naming pattern as staff permissions.
Orders.*
Orders.List (index)
Orders.Create (store)

Also, prefix the language string keys with `text_`, `label_` or `column_` to keep it consistent with other language files.

**Comment by ryanmitchell** [comment]
All done and pushed to the same PR
