### ISSUE TITLE
Error Deleting Menus using API

### ISSUE THREAD

**Issue by amr3ssam** [tastyigniter/ti-ext-api#43]
Using DELETE /api/menus/:menu_id

item should be deleted instead i got this error

{
    "status_code": 500,
    "message": "Call to a member function isSuperUser() on null",
    "debug": {
        "line": 25,
        "file": "/var/www/vhosts/httpdocs/app/admin/classes/User.php",
        "class": "Symfony\\Component\\Debug\\Exception\\FatalThrowableError",
        "trace": [
            "#0 /var/www/vhosts/httpdocs/app/admin/traits/Locationable.php(102): Admin\\Classes\\User->isSuperUser()",
            "#1 /var/www/vhosts/httpdocs/app/admin/traits/Locationable.php(29): Admin\\Models\\Menus_model->detachLocationsOnDelete()",
            "#2 /var/www/vhosts/httpdocs/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(369): Admin\\Models\\Menus_model::Admin\\Traits\\{closure}(Object(Admin\\Models\\Menus_model))",
            "#3 /var/www/vhosts/httpdocs/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(218): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('eloquent.deleti...', Array)",
            "#4 /var/www/vhosts/httpdocs/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(191): Illuminate\\Events\\Dispatcher->dispatch('eloquent.deleti...', Array, true)",
            "#5 /var/www/vhosts//httpdocs/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php(189): Illuminate\\Events\\Dispatcher->until('eloquent.deleti...', Object(Admin\\Models\\Menus_model))",
            "#6 /var/www/vhosts/httpdocs/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(898): Illuminate\\Database\\Eloquent\\Model->fireModelEvent('deleting')",
            "#7 /var/www/vhosts/httpdocs/extensions/igniter/api/actions/RestController.php(176): Illuminate\\Database\\Eloquent\\Model->delete()",
            "#8 [internal function]: Igniter\\Api\\Actions\\RestController->destroy('45')",
            "#9 /var/www/vhosts/httpdocs/vendor/tastyigniter/flame/src/Traits/ExtendableTrait.php(428): call_user_func_array(Array, Array)",
            "#10 /var/www/vhosts/httpdocs/vendor/tastyigniter/flame/src/Support/Extendable.php(42): Igniter\\Flame\\Support\\Extendable->extendableCall('destroy', Array)",
            "#11 [internal function]: Igniter\\Flame\\Support\\Extendable->__call('destroy', Array)",
            "#12 /var/www/vhosts/httpdocs/extensions/igniter/api/classes/ApiController.php(80): call_user_func_array(Array, Array)",
            "#13 /var/www/vhosts/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Igniter\\Api\\Classes\\ApiController->callAction('destroy', Array)",
            "#14 /var/www/vhosts/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Igniter\\Api\\ApiResources\\Menus), 'destroy')",
            "#15 /var/www/vhosts/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()",
            "#16 /var/www/vhosts/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Routing\\Route->run()",
            "#17 /var/www/vhosts/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))",
            "#18 /var/www/vhosts/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
            "#19 /var/www/vhosts/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))",
            "#20 /var/www/vhosts/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
            "#21 /var/www/vhosts/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle(Object(Illuminate\\Http\\Request), Object(Closure), 60, '1')",
            "#22 /var/www/vhosts/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
            "#23 /var/www/vhosts/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
            "#24 /var/www/vhosts/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))",
            "#25 /var/www/vhosts/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))",
            "#26 /var/www/vhosts/httpdocs/vendor/october/rain/src/Router/CoreRouter.php(20): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))",
            "#27 /var/www/vhosts/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): October\\Rain\\Router\\CoreRouter->dispatch(Object(Illuminate\\Http\\Request))",
            "#28 /var/www/vhosts/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))",
            "#29 /var/www/vhosts/httpdocs/vendor/tastyigniter/flame/src/Setting/Middleware/SaveSetting.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
            "#30 /var/www/vhosts/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Igniter\\Flame\\Setting\\Middleware\\SaveSetting->handle(Object(Illuminate\\Http\\Request), Object(Closure))",
            "#31 /var/www/vhosts/httpdocs/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
            "#32 /var/www/vhosts/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))",
            "#33 /var/www/vhosts/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
            "#34 /var/www/vhosts/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))",
            "#35 /var/www/vhosts/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
            "#36 /var/www/vhosts/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))",
            "#37 /var/www/vhosts/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
            "#38 /var/www/vhosts/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))",
            "#39 /var/www/vhosts/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
            "#40 /var/www/vhosts/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
            "#41 /var/www/vhosts/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))",
            "#42 /var/www/vhosts/httpdocs/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))",
            "#43 {main}"
        ]
    }
}

API Version 0.3.0
Tastigniter Version 3.0.4-beta.26

**Comment by ryanmitchell** [comment]
Can you upgrade to the latest API and TI version?
