### ISSUE TITLE
 (patch) https://tasty.test.com/api/orders/nnn

### ISSUE THREAD

**Issue by jhaynes059** [tastyigniter/ti-ext-api#44]
(patch)https://tasty.test.com/api/orders/103  with body {
  "status_id": 2
} fails with status 422 

with message 
{
    "message": "Failed to validate request parameters",
    "errors": {
        "first_name": [
            "The First Name field is required."
        ],
        "last_name": [
            "The Last Name field is required."
        ],
        "order_type": [
            "The Order Type field is required."
        ]
    },
    "status_code": 422
**Expected behavior:**
update order status_id from 1 to 2

**Actual behavior:**
Got error saying additional parameters were required
{
    "message": "Failed to validate request parameters",
    "errors": {
        "first_name": [
            "The First Name field is required."
        ],
        "last_name": [
            "The Last Name field is required."
        ],
        "order_type": [
            "The Order Type field is required."
        ]
    },
    "status_code": 422

**Reproduce steps:**
I can DM a tester with the correct url if needed.

1) method Get  https://tasty.test.com/api/orders/104, works fine, "status_id": 1
2)  method Patch https://tasty.test.com/api/orders/104 with body { "status_id": 2 }
Rather than change the status, Iget the following message:
{
    "message": "Failed to validate request parameters",
    "errors": {
        "first_name": [
            "The First Name field is required."
        ],
        "last_name": [
            "The Last Name field is required."
        ],
        "order_type": [
            "The Order Type field is required."
        ]
    },
    "status_code": 422

**Version:**
igniter v3.0.4 beta .28

**Additional Information:**
(Additional information, if any)

**Comment by ryanmitchell** [comment]
This was fixed by an earlier PR and is available in 1.0.1. Going to close this. Re-open if you still have issues.
