### ISSUE TITLE
documentation on reservation endpoint not correct

### ISSUE THREAD

**Issue by noromamai** [tastyigniter/ti-ext-api#48]
reservations.md shows example payload:

{
  "reservation_id": 1,
  "location_id": 1,
  "table_id": 1,
  "guest_num": 2,
  "first_name": "Ryder",
  "last_name": "Anthony",
  "email": "xigakube@mailinator.net",
  "telephone": "+1 (828) 231-8892",
  "comment": "Cillum eum cupidatat",
  "reserve_date_time": "2020-06-26 19:35:00"
}

- reservation_id should be left since this is for creating a new reservation
- reserve_date_time is not accepted. there should be two seperate fields for "reserve_date" and "reserve_time"

**Comment by ryanmitchell** [comment]
Can you create a pull request with the changes?

**Comment by jacuna88** [comment]
Hi, I have created a pull request with these changes
