### ISSUE TITLE
[Feature]: Filters results by relationship 

### ISSUE THREAD

**Issue by devexsolutions** [tastyigniter/ti-ext-api#51]
### What is the feature?

I think it is really necessary, to be able to filter the results in the calls to the endpoints, when you work with multiple locations. For example, if I want to obtain the categories of a single location, the API does not allow me to discriminate the results, so it returns all the categories, regardless of the location to which they belong.
For instance:
**/api/categories?include=locations&filter[locations][id]=1**. It would also be necessary to obtain the menus of each location, filtering by category
**/api/menus?include=categories&filter[categories][id]=1**.

### Version

3.0.4 (Stable)

**Comment by ryanmitchell** [comment]
You can already filter on many of the end points (e.g. https://github.com/tastyigniter/ti-ext-api/blob/master/docs/menus.md#list-menus)

Are you prepared to work on a PR to make categories support similar filter parameters?

**Comment by devexsolutions** [comment]
I can try it. I have experience developing in laravel.

**Comment by ryanmitchell** [comment]
Should just be a case of adding a scopeListFrontend function to the categories_model - you can borrow the logic from menus model almost like for like

**Comment by devexsolutions** [comment]
Can you give me an example of the so-called menus with category as a parameter?
Thanks.

**Comment by ryanmitchell** [comment]
/api/menus?include=categories&category=appetiser
