### ISSUE TITLE
POS System based on the API With Flutter

### ISSUE THREAD

**Issue by BlueRayNL** [tastyigniter/ti-ext-api#62]
### What is the feature?

Hi Guy's.

i'm working on a POS system voor tasty. however I need some help.
with flutter I normally use a rest API, do we have any good documentation on this topic for tasty?

thanks in advance :)

### Version

3.0.6

**Comment by ryanmitchell** [comment]
There is a docs folder in this  extension with markdown files containing all the end points and parameters.
