### ISSUE TITLE
[Bug]: I can successfully login to my account even if my account is not active.

### ISSUE THREAD

**Issue by BaoNguyenSE** [tastyigniter/ti-ext-api#67]
### What happened?

I can successfully login to my account even if my account is not active.

### What did you expect to happen?

Throw error when i login without account actived

### Version

3.2.x

**Comment by ryanmitchell** [comment]
I've opened a PR to verify the user is still activated: https://github.com/tastyigniter/ti-ext-api/pull/68
Let me know if this works for you.
