### ISSUE TITLE
POST request create a new Category test

### ISSUE THREAD

**Issue by texas16** [tastyigniter/ti-ext-api#7]
@ryanmitchell, testing POST request with the following payload is as `{ "name":"Soup", "status":true }` but I am getting the following error. I am using the latest feature branch -` add-api-reference-docs`

```
status_code: 500,
message: "SQLSTATE[HY093]: Invalid parameter number: mixed named and positional parameters (SQL: insert into `ti_categories` (`{ __"name":_"Soup", __"status":_true }`, `permalink_slug`, `parent_id`, `nest_left`, `nest_right`, `priority`) values (?, ?, ?, 19, 20, 10))",
```

**Comment by ryanmitchell** [comment]
The payload should be json format, e.g.

curl -i -X POST \
-H "Accept: application/json" \
-H "Content-Type: application/json" \
--data '{"name":"Soup","status":true}' \
https://your.url/api/categories
