### ISSUE TITLE
[Bug]:unable to create order

### ISSUE THREAD

**Issue by abwhb** [tastyigniter/ti-ext-api#72]
### What happened?

On post call order API returns with: 
`"message": "Array to string conversion",
	"status_code": 500,
	"debug": {
		"line": 609,
		"file": "\xyz/vendor\/laravel\/framework\/src\/Illuminate\/Support\/Str.php",
		"class": "ErrorException",`

I'm using the payload provided in the document to create an order.

Here's the store link:  `https://ck.seatqr.co/`

The post call is set to public if anyone would like to recreate the bug. 

### What did you expect to happen?

Order created with the payload provided in the documentation

### Version

3.2.x

### What browser are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Relevant log output

```shell
"message": "Array to string conversion",
	"status_code": 500,
	"debug": {
		"line": 609,
		"file": "\xyz/vendor\/laravel\/framework\/src\/Illuminate\/Support\/Str.php",
		"class": "ErrorException",
```

**Comment by sampoyigi** [comment]
This issue has no reproducible steps. Please reopen this issue if it still occurs, with a set of reproducible steps.
