### ISSUE TITLE
[Bug]: Issue in Order creation API  

### ISSUE THREAD

**Issue by vaibhavmalushte** [tastyigniter/ti-ext-api#84]
### What happened?

I am unsing following playload to create Order. 
`
{
    "location_id": 1,
    "first_name": "asdadasdasdasdasdas",
    "last_name": "aasdadadasd",
    "email": "asdas@asd.com",
    "telephone": "+1 (604) 376-2674",
    "comment": "Give me my food",
    "order_type": "collection",
    "order_date": "2022-11-01",
    "order_time": "10:00",
    "payment": "cod",
    "status_id": 1,
    "status_comment": "My comment",
    "order_menus": [
        {
            "rowId": 0,
            "id": 1,
            "name": "Puff-Puff",
            "qty": 3,
            "price": "4.9900",
            "subtotal": "14.9700",
            "comment": "",
            "options": []
        }
    ],
    "order_totals": [
        {
            "code": "total",
            "title": "Total",
            "value": 10,
            "priority": 1
        }
    ],
    "order_total": 10.00
}
`

Reeceived 201 response.

`
{"data":{"type":"orders","id":"10","attributes":{"hash":"d42a85c3d81317df8a6f839ec392f276","ip_address":"134.238.252.228","user_agent":"PostmanRuntime\/7.30.0","updated_at":"2023-01-11T10:27:46.000000Z","created_at":"2023-01-11T10:27:46.000000Z","order_id":10,"customer_name":" ","order_type_name":null,"order_date_time":null,"formatted_address":null,"status_name":null,"status":null,"currency":"GBP","order_totals":[],"order_menus":[]}}}
`

### What did you expect to happen?

It shoud create Order, However when checked in admin console, it looks like below screenshot.
<img width="1520" alt="image" src="https://user-images.githubusercontent.com/33909/211805026-f7322788-049a-4538-88af-0b9b652733b9.png">

Checked in DB, the orders table looks like 

<img width="1669" alt="image" src="https://user-images.githubusercontent.com/33909/211805619-de15f26a-74bb-49c6-9686-4fa4ea007de4.png">

Where as orders created from Website looks like this.

<img width="1669" alt="image" src="https://user-images.githubusercontent.com/33909/211806151-67cd54c2-e1b3-48c8-9207-4a8b84a84e90.png">

### Version

3.5.x

### Relevant log output

```shell
No error logs.
```

**Comment by vaibhavmalushte** [comment]
My bad, the payload type was test to text, which I have changed to JSON and it started working. Closing this issue / bug.

**Comment by waltermvp** [comment]
@vaibhavmalushte can you please share the full curl and steps to set this up? (block out any api keys). I am trying to figure out how to create an order programatically.
